#!/usr/bin/env bash

function send_notification() {
	brightness=$(printf "%.0f\n" $(brillo -G))
	dunstify -a "change-brightness" -u low -r "9993" -h int:value:"$brightness" -i "$HOME/.config/dunst/brightness-$1.svg" "Brightness: ${brightness}%" -t 2000
}

case $1 in
	up)
		brillo -q -A 5
		send_notification $1
		;;
	down)
		brillo -q -U 5
		send_notification $1
		;;
esac
