#!/usr/bin/env bash
function send_notification() {
	volume=$(pulsemixer --get-volume)
	dunstify -a "change-volume" -u low -r "9993" -h int:value:"$volume" -i "$HOME/.config/dunst/volume-$1.svg" "Volume: ${volume}%" -t 2000
}

case $1 in
	up)
		xrandr --output eDP-1 --brightness 
		pulsemixer --change-volume +10
		send_notification $1
		;;
	down)
		pulsemixer --change-volume -10
		send_notification $1
		;;
esac
